services:
  cms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-canteen-cms
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "com.docker.compose.project=cms"
      - "com.docker.compose.service=cms-app"
      - "description=Smart Canteen Management System"
      - "version=1.0"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  cms-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smart-canteen-cms-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - "com.docker.compose.project=cms"
      - "com.docker.compose.service=cms-dev"
      - "description=Smart Canteen Management System (Development)"
      - "version=1.0"
    command: npm run dev
    profiles:
      - dev 